# Generated by Django 4.2.7 on 2026-05-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
                ('admission_type', models.CharField(choices=[('REGULAR', 'Regular'), ('TRANSFER', 'Transfer'), ('SCHOLARSHIP', 'Scholarship')], default='REGULAR', max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('father_name', models.CharField(max_length=200)),
                ('father_phone', models.CharField(blank=True, max_length=17, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_phone', models.CharField(blank=True, max_length=17, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='students/documents/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='students/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('BEHAVIORAL', 'Behavioral'), ('MEDICAL', 'Medical'), ('GENERAL', 'General'), ('ACHIEVEMENT', 'Achievement'), ('CONCERN', 'Concern')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Note',
                'verbose_name_plural': 'Student Notes',
                'db_table': 'student_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_CARD', 'ID Card'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('MARKSHEET', 'Marksheet'), ('MEDICAL', 'Medical Certificate'), ('CHARACTER', 'Character Certificate'), ('PHOTO', 'Photograph'), ('OTHER', 'Other')], max_length=30)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='students/documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'db_table': 'student_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achievement_type', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('LEADERSHIP', 'Leadership'), ('COMPETITION', 'Competition'), ('SERVICE', 'Community Service'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='students/achievements/')),
                ('awarded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_achievements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Achievement',
                'verbose_name_plural': 'Student Achievements',
                'db_table': 'student_achievements',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'guardians',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='students_admissi_664d58_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_name', 'section'], name='students_class_n_32ce71_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status_3ac771_idx'),
        ),
    ]
